export interface VipPlanListData {
  id: string;
  no: string;
  productKey: string;
  tags: string;
  price: number;
  offerPrice: number;
  validity: string;
  validityType: string;
  date: string;
  isActive: boolean;
}

export const initialVipPlanListData: VipPlanListData[] = [
  {
    id: "01",
    no: "01",
    productKey: "VIP-Key",
    tags: "premium",
    price: 19.99,
    offerPrice: 14.99,
    validity: "1 Month",
    validityType: "Months",
    date: "2025-08-01",
    isActive: true,
  },
  {
    id: "02",
    no: "02",
    productKey: "VIP-Key",
    tags: "premium",
    price: 19.99,
    offerPrice: 14.99,
    validity: "1 Month",
    validityType: "Months",
    date: "2025-08-01",
    isActive: true,
  },
  {
    id: "03",
    no: "03",
    productKey: "VIP-Key",
    tags: "premium",
    price: 19.99,
    offerPrice: 14.99,
    validity: "1 Month",
    validityType: "Months",
    date: "2025-08-01",
    isActive: true,
  },
  {
    id: "04",
    no: "04",
    productKey: "VIP-Key",
    tags: "premium",
    price: 19.99,
    offerPrice: 14.99,
    validity: "1 Month",
    validityType: "Months",
    date: "2025-08-01",
    isActive: true,
  },
  {
    id: "05",
    no: "05",
    productKey: "VIP-Key",
    tags: "premium",
    price: 19.99,
    offerPrice: 14.99,
    validity: "1 Month",
    validityType: "Months",
    date: "2025-08-01",
    isActive: true,
  },
  {
    id: "06",
    no: "06",
    productKey: "VIP-Key",
    tags: "premium",
    price: 19.99,
    offerPrice: 14.99,
    validity: "1 Month",
    validityType: "Months",
    date: "2025-08-01",
    isActive: true,
  },
  {
    id: "07",
    no: "07",
    productKey: "VIP-Key",
    tags: "premium",
    price: 19.99,
    offerPrice: 14.99,
    validity: "1 Month",
    validityType: "Months",
    date: "2025-08-01",
    isActive: true,
  },
  {
    id: "08",
    no: "08",
    productKey: "VIP-Key",
    tags: "premium",
    price: 19.99,
    offerPrice: 14.99,
    validity: "1 Month",
    validityType: "Months",
    date: "2025-08-01",
    isActive: true,
  },
  {
    id: "09",
    no: "09",
    productKey: "VIP-Key",
    tags: "premium",
    price: 19.99,
    offerPrice: 14.99,
    validity: "1 Month",
    validityType: "Months",
    date: "2025-08-01",
    isActive: true,
  },
  {
    id: "10",
    no: "10",
    productKey: "VIP-Key",
    tags: "premium",
    price: 19.99,
    offerPrice: 14.99,
    validity: "1 Month",
    validityType: "Months",
    date: "2025-08-01",
    isActive: true,
  },
];
