export interface Entry {
  id: number;
  title: string;
  tags: string;
  authorName: string;
  authorAvatar: string;
  description: string;
  views: string;
  likes: string;
  comments: string;
  poster: string;
}

export const entriesData: Entry[] = [
  {
    id: 1,
    title: "Forever After, Never Again to born",
    tags: "Love After Divorce, Heiress",
    authorName: "Tom Konkle",
    authorAvatar: "/images/contest/avatar.jpg",
    description: "Based on true events, in our darkest of times, the Tickle Mons...",
    views: "866k",
    likes: "866k",
    comments: "866k",
    poster: "/images/contest/GalleryofContestcardPoster.png",
  },
  {
    id: 2,
    title: "Forever After, Never Again to born",
    tags: "Love After Divorce, Heiress",
    authorName: "Tom Konkle",
    authorAvatar: "/images/contest/avatar.jpg",
    description: "Based on true events, in our darkest of times, the Tickle Mons...",
    views: "866k",
    likes: "866k",
    comments: "866k",
    poster: "/images/contest/GalleryofContestcardPoster.png",
  },
  {
    id: 3,
    title: "Forever After, Never Again to born",
    tags: "Love After Divorce, Heiress",
    authorName: "Tom Konkle",
    authorAvatar: "/images/contest/avatar.jpg",
    description: "Based on true events, in our darkest of times, the Tickle Mons...",
    views: "866k",
    likes: "866k",
    comments: "866k",
    poster: "/images/contest/GalleryofContestcardPoster.png",
  },
  {
    id: 4,
    title: "Forever After, Never Again to born",
    tags: "Love After Divorce, Heiress",
    authorName: "Tom Konkle",
    authorAvatar: "/images/contest/avatar.jpg",
    description: "Based on true events, in our darkest of times, the Tickle Mons...",
    views: "866k",
    likes: "866k",
    comments: "866k",
    poster: "/images/contest/GalleryofContestcardPoster.png",
  },
  {
    id: 5,
    title: "Forever After, Never Again to born",
    tags: "Love After Divorce, Heiress",
    authorName: "Tom Konkle",
    authorAvatar: "/images/contest/avatar.jpg",
    description: "Based on true events, in our darkest of times, the Tickle Mons...",
    views: "866k",
    likes: "866k",
    comments: "866k",
    poster: "/images/contest/GalleryofContestcardPoster.png",
  },
  {
    id: 6,
    title: "Forever After, Never Again to born",
    tags: "Love After Divorce, Heiress",
    authorName: "Tom Konkle",
    authorAvatar: "/images/contest/avatar.jpg",
    description: "Based on true events, in our darkest of times, the Tickle Mons...",
    views: "866k",
    likes: "866k",
    comments: "866k",
    poster: "/images/contest/GalleryofContestcardPoster.png",
  },
  {
    id: 7,
    title: "Forever After, Never Again to born",
    tags: "Love After Divorce, Heiress",
    authorName: "Tom Konkle",
    authorAvatar: "/images/contest/avatar.jpg",
    description: "Based on true events, in our darkest of times, the Tickle Mons...",
    views: "866k",
    likes: "866k",
    comments: "866k",
    poster: "/images/contest/GalleryofContestcardPoster.png",
  },
  {
    id: 8,
    title: "Forever After, Never Again to born",
    tags: "Love After Divorce, Heiress",
    authorName: "Tom Konkle",
    authorAvatar: "/images/contest/avatar.jpg",
    description: "Based on true events, in our darkest of times, the Tickle Mons...",
    views: "866k",
    likes: "866k",
    comments: "866k",
    poster: "/images/contest/GalleryofContestcardPoster.png",
  },
  {
    id: 9,
    title: "Forever After, Never Again to born",
    tags: "Love After Divorce, Heiress",
    authorName: "Tom Konkle",
    authorAvatar: "/images/contest/avatar.jpg",
    description: "Based on true events, in our darkest of times, the Tickle Mons...",
    views: "866k",
    likes: "866k",
    comments: "866k",
    poster: "/images/contest/GalleryofContestcardPoster.png",
  },
  {
    id: 10,
    title: "Forever After, Never Again to born",
    tags: "Love After Divorce, Heiress",
    authorName: "Tom Konkle",
    authorAvatar: "/images/contest/avatar.jpg",
    description: "Based on true events, in our darkest of times, the Tickle Mons...",
    views: "866k",
    likes: "866k",
    comments: "866k",
    poster: "/images/contest/GalleryofContestcardPoster.png",
  },
  {
    id: 11,
    title: "Forever After, Never Again to born",
    tags: "Love After Divorce, Heiress",
    authorName: "Tom Konkle",
    authorAvatar: "/images/contest/avatar.jpg",
    description: "Based on true events, in our darkest of times, the Tickle Mons...",
    views: "866k",
    likes: "866k",
    comments: "866k",
    poster: "/images/contest/GalleryofContestcardPoster.png",
  },
  {
    id: 12,
    title: "Forever After, Never Again to born",
    tags: "Love After Divorce, Heiress",
    authorName: "Tom Konkle",
    authorAvatar: "/images/contest/avatar.jpg",
    description: "Based on true events, in our darkest of times, the Tickle Mons...",
    views: "866k",
    likes: "866k",
    comments: "866k",
    poster: "/images/contest/GalleryofContestcardPoster.png",
  },
];