export interface FilmData {
  id: string;
  no: string;
  image: string;
  category: string;
  name: string;
  description: string;
  date: string;
  totalEpisodes: number;
  maxAdsForFreeView: number;
  isBanner: boolean;
  isTrending: boolean;
  isActive: boolean;
  episodes: string;
}

export const initialFilmsData: FilmData[] = [
  {
    id: "1",
    no: "01",
    image: "/images/Poster 4.png",
    category: "Love",
    name: "Lover",
    description: "No Description",
    date: "31/12/2025",
    totalEpisodes: 24,
    maxAdsForFreeView: 5,
    isBanner: true,
    isTrending: false,
    isActive: true,
    episodes: "View",
  },
  {
    id: "2",
    no: "01",
    image: "/images/Poster 4.png",
    category: "Love",
    name: "Lover",
    description: "No Description",
    date: "31/12/2025",
    totalEpisodes: 24,
    maxAdsForFreeView: 5,
    isBanner: true,
    isTrending: false,
    isActive: true,
    episodes: "View",
  },
  {
    id: "3",
    no: "01",
    image: "/images/Poster 4.png",
    category: "Love",
    name: "Lover",
    description: "No Description",
    date: "31/12/2025",
    totalEpisodes: 24,
    maxAdsForFreeView: 5,
    isBanner: true,
    isTrending: false,
    isActive: true,
    episodes: "View",
  },
  {
    id: "4",
    no: "01",
    image: "/images/Poster 4.png",
    category: "Love",
    name: "Lover",
    description: "No Description",
    date: "31/12/2025",
    totalEpisodes: 24,
    maxAdsForFreeView: 5,
    isBanner: true,
    isTrending: false,
    isActive: true,
    episodes: "View",
  },
  {
    id: "5",
    no: "01",
    image: "/images/Poster 4.png",
    category: "Love",
    name: "Lover",
    description: "No Description",
    date: "31/12/2025",
    totalEpisodes: 24,
    maxAdsForFreeView: 5,
    isBanner: true,
    isTrending: false,
    isActive: true,
    episodes: "View",
  },
  {
    id: "6",
    no: "01",
    image: "/images/Poster 4.png",
    category: "Love",
    name: "Lover",
    description: "No Description",
    date: "31/12/2025",
    totalEpisodes: 24,
    maxAdsForFreeView: 5,
    isBanner: true,
    isTrending: false,
    isActive: true,
    episodes: "View",
  },
  {
    id: "7",
    no: "01",
    image: "/images/Poster 4.png",
    category: "Love",
    name: "Lover",
    description: "No Description",
    date: "31/12/2025",
    totalEpisodes: 24,
    maxAdsForFreeView: 5,
    isBanner: true,
    isTrending: false,
    isActive: true,
    episodes: "View",
  },
  {
    id: "8",
    no: "01",
    image: "/images/Poster 4.png",
    category: "Love",
    name: "Lover",
    description: "No Description",
    date: "31/12/2025",
    totalEpisodes: 24,
    maxAdsForFreeView: 5,
    isBanner: true,
    isTrending: false,
    isActive: true,
    episodes: "View",
  },
  {
    id: "9",
    no: "01",
    image: "/images/Poster 4.png",
    category: "Love",
    name: "Lover",
    description: "No Description",
    date: "31/12/2025",
    totalEpisodes: 24,
    maxAdsForFreeView: 5,
    isBanner: true,
    isTrending: false,
    isActive: true,
    episodes: "View",
  },
];